service:
  name: sample-serverless-simple-api

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
provider:
  name: aws
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${opt:stage, self:custom.defaultStage}}
  runtime: python3.8
  stackName: sample-serverless-simple-api
  apiName: sample-serverless-simple-api
  logRetentionInDays: 7
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
        - lambda:GetLayerVersion
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"
  environment:
    DEFAULT_DATA_LIMIT: "20"
    ENV: ${self:custom.environments.ENV}

custom:
  defaultStage: itg
  profiles:
    itg: sls-itg
    stg: sls-stg
  pythonRequirements:
    dockerizePip: true
    usePipenv: true
    layer: true
  environments: ${file(./config/config.${opt:stage, self:custom.defaultStage}.yaml)}

package:
  individually: true
  exclude:
    - config/**
    - .git/**
    - .venv/**
    - tests/**
    - sample/**
    - README.md
    - .pytest_cache/**
    - .circleci/**
    - package**
    - Pipfile**

functions:
  ListItems:
    name: list_items
    handler: src/handlers/list_items.handler
    description: "販促品一覧"
    layers:
      - !Ref PythonRequirementsLambdaLayer
      - !Ref ShareLambdaLayer
    events:
      - http:
          path: /items
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                limit: false

layers:
  Share:
    path: src/layers/share
    name: share
    description: sample Layer
    # compatibleRuntimes:
    #   - python3.8
    retain: false

resources:
  Resources:
    ItemTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: Items
        AttributeDefinitions:
          - { AttributeName: item_id, AttributeType: S }
        KeySchema:
          - { AttributeName: item_id, KeyType: HASH }
        BillingMode: PAY_PER_REQUEST
