service:
  name: sample-serverless-simple-api

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters
provider:
  name: aws
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${opt:stage, self:custom.defaultStage}}
  runtime: python3.8
  stackName: sample-serverless-simple-api
  apiName: sample-serverless-simple-api
  logRetentionInDays: 7
  versionFunctions: false
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
        - lambda:GetLayerVersion
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "*"
  environment:
    DEFAULT_DATA_LIMIT: "20"
    ENV: ${self:custom.environments.ENV}
    AUTH0_DOMAIN: ${self:custom.environments.AUTH0_DOMAIN}
    TOKEN_ISSUER: ${self:custom.environments.TOKEN_ISSUER}
    AUTH0_AUDIENCE: ${self:custom.environments.AUTH0_AUDIENCE}
    LOG_LEVEL: ${self:custom.environments.LOG_LEVEL}
    POWERTOOLS_SERVICE_NAME: ${self:custom.environments.ENV}-sample-serverless-api

custom:
  defaultStage: itg
  profiles:
    itg: sls-itg
    stg: sls-stg
  pythonRequirements:
    dockerizePip: true
    usePipenv: true
    layer: true
  environments: ${file(./config/config.${opt:stage, self:custom.defaultStage}.yaml)}

package:
  individually: true
  exclude:
    - config/**
    - .git/**
    - .venv/**
    - tests/**
    - sample/**
    - README.md
    - .pytest_cache/**
    - .circleci/**
    - package**
    - Pipfile**
    - node_modules/**
    - docs/**
    - cfn/**

functions:
  # カスタムオーソライザー
  Auth:
    name: authorizer
    handler: src/handlers/service/authorizer.handler
    layers:
      - !Ref PythonRequirementsLambdaLayer
      - !Ref CommonLambdaLayer

  ListItems:
    name: list_items
    handler: src/handlers/list_items.handler
    description: "販促品一覧"
    layers:
      - !Ref PythonRequirementsLambdaLayer
      - !Ref CommonLambdaLayer

  GetItem:
    name: get_item
    handler: src/handlers/get_item.handler
    description: "販促品取得"
    layers:
      - !Ref PythonRequirementsLambdaLayer
      - !Ref CommonLambdaLayer

layers:
  Common:
    path: src/layers/share
    name: common
    description: sample-serverless-simple-api layer
    retain: false

resources:
  Resources:
    ItemTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        TableName: Items
        AttributeDefinitions:
          - { AttributeName: item_id, AttributeType: S }
        KeySchema:
          - { AttributeName: item_id, KeyType: HASH }
        BillingMode: PAY_PER_REQUEST
    # API Gateway
    ApiGatewayRestApi:
      Type: "AWS::ApiGateway::RestApi"
      Properties:
        Body: ${file(./templates/swagger.yml)}
    ListItemsPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName: list_items
        Action: "lambda:InvokeFunction"
        Principal: "apigateway.amazonaws.com"
        SourceArn: "arn:aws:execute-api:#{AWS::Region}:#{AWS::AccountId}:pe0551op28/*/GET/items"
    ApiGatewayRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /service-role/
        RoleName: apigateway
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - apigateway.amazonaws.com
              Action:
                - sts:AssumeRole
    ApiGatewayDeployment:
      Type: AWS::ApiGateway::Deployment
      Properties:
        RestApiId: !Ref ApiGatewayRestApi
        StageName: ${opt:stage, self:custom.defaultStage}
      DependsOn: ApiGatewayRestApi
