service:
  name: sample-serverless-api

plugins:
  - serverless-python-requirements
  - serverless-pseudo-parameters

provider:
  name: aws
  region: ap-northeast-1
  stage: ${opt:stage, self:custom.defaultStage}
  profile: ${self:custom.profiles.${opt:stage, self:custom.defaultStage}}
  runtime: python3.8
  stackName: sample-serverless-api
  apiName: sample-serverless-api
  logRetentionInDays: 7
  iamRoleStatements:
    - Effect: Allow
      Action:
        - logs:CreateLogGroup
        - logs:CreateLogStream
        - logs:PutLogEvents
        - secretsmanager:GetSecretValue
        - lambda:GetLayerVersion
      Resource: "*"
  environment:
    DEFAULT_DATA_LIMIT: 20
    ENV: ${self:custom.environments.ENV}

custom:
  defaultStage: itg
  profiles:
    itg: sls-itg
    stg: sls-stg
  pythonRequirements:
    dockerizePip: true
    usePipenv: true
    layer: true
  environments: ${file(./config/config.${opt:stage, self:custom.defaultStage}.yaml)}
  secret: ${file(./config/secret/secret.${opt:stage, self:custom.defaultStage}.yaml)}

package:
  individually: true
  exclude:
    - config/**
    - .git/**
    - .venv/**
    - tests
    - sample/**
    - README.md

functions:
  listPromotionalItems:
    name: list_promotional_items
    handler: src/handlers/list_promotional_items.handler
    description: "販促品一覧"
    layers:
      - !Ref PythonRequirementsLambdaLayer
    events:
      - http:
          path: /promotional_items
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                limit: false
